Run cypress tests using github action
The github action assumes that the cypress container is already running from the e2e bundle

diff --git a/github-actions/run-cypress-tests/action.yml b/github-actions/run-cypress-tests/action.yml
--- a/github-actions/run-cypress-tests/action.yml
+++ b/github-actions/run-cypress-tests/action.yml
@@ -4,26 +4,32 @@ description: 'Runs e2e tests'
 runs:
   using: 'composite'
   steps:
-    - name: Run Cypress tests in started environment
-      # I have checked the code of this github action and haven't found anything malicous in it. (Tamas Pallos @ 7.6.2022)
-      uses: nick-fields/retry@02a3f09f1566ff8b95fd3b7896b51296ac01e264
+    - name: Run tests using the e2e docker bundle's cypress container
+      run: |
+        docker exec cypress \
+          bash -c "yarn test:e2e"
+      shell: bash
+
+    - name: Retrieve test reports from container
+      # should be run even if the tests fail
+      if: always()
+      run: |
+        docker cp cypress:/e2e/cypress/reports ${{ github.workspace }}/cypress/ || echo "No reports"
+      shell: bash
+
+    - name: Upload test reports as an artifact
+      # should be run even if the tests fail
+      if: always()
+      uses: actions/upload-artifact@v3
       with:
-        timeout_minutes: 30
-        max_attempts: 3
-        shell: bash
-        command: |
-          # Get current date as a postfix for individual runs
-          CURRENT_DATE=$(date +%s)
+        name: cypress-docker-reports
+        path: |
+          ${{ github.workspace }}/cypress/reports
 
-          # Run tests
-          docker run \
-            --name "cypress-tests" \
-            --network="host" \
-            hsldevcom/jore4-cypress:latest \
-            bash -c "cypress run --browser chrome"
-
-          # Retrieve test results from docker container to the reports folder
-          docker cp cypress-tests:/reports/. "${{ github.workspace }}/reports/${CURRENT_DATE}/" || echo "No reports"
-
-          # Cleanup test container
-          docker rm --force cypress-tests
+    - name: Fail the job
+      # should fail the job if the tests fail
+      if: ${{ failure() }}
+      run: |
+        echo "E2E tests failed! See reports in the workflow's artifacts"
+        exit 1
+      shell: bash
