fail the job

diff --git a/github-actions/run-cypress-tests/action.yml b/github-actions/run-cypress-tests/action.yml
--- a/github-actions/run-cypress-tests/action.yml
+++ b/github-actions/run-cypress-tests/action.yml
@@ -4,17 +4,32 @@ description: 'Runs e2e tests'
 runs:
   using: 'composite'
   steps:
-    - name: Run Cypress tests in started environment
+    - name: Run tests using the e2e docker bundle's cypress container
       run: |
-        # Get current date as a postfix for individual runs
-        CURRENT_DATE=$(date +%s)
-
-        # Run tests using the e2e docker bundle's cypress container
         docker exec cypress \
           bash -c "yarn test:e2e"
+      shell: bash
 
-        # Retrieve test results from docker container to the reports folder
-        docker cp cypress-tests:/reports/. "${{ github.workspace }}/reports/${CURRENT_DATE}/" || echo "No reports"
+    - name: Retrieve test reports from container
+      # should be run even if the tests fail
+      if: always()
+      run: |
+        docker cp cypress:/e2e/cypress/reports ${{ github.workspace }}/cypress/ || echo "No reports"
+      shell: bash
 
-        # Cleanup test container
-        docker rm --force cypress-tests
+    - name: Upload test reports as an artifact
+      # should be run even if the tests fail
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: cypress-docker-reports
+        path: |
+          ${{ github.workspace }}/cypress/reports
+
+    - name: Fail the job The job has failed
+      # should fail the job if the tests fail
+      if: ${{ failure() }}
+      run: |
+        echo "E2E tests failed! See reports in the workflow's artifacts"
+        exit 1
+      shell: bash
